trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: A
  jobs:
  - deployment: A1
    environment: Test
    strategy:
     runOnce:
       deploy:
        steps:
        - bash: echo "##vso[task.setvariable variable=shouldrun;isOutput=true]false"
          name: printvar
        - pwsh: |
            Write-Host "$(Agent.JobName)"
            Write-Host "$(System.JobName)"
        

- stage: B
  condition: and(succeeded(), ne(dependencies.A.outputs['A1.printvar.shouldrun'], 'true'))
  dependsOn: A
  jobs:
  - job: B1
    steps:
    - script: echo hello from Stage B
    cancelTimeoutInMinutes: 

- stage: C
  condition: and(succeeded(), eq(dependencies.A.outputs['A1.printvar.shouldrun'], 'false'))
  dependsOn: A
  jobs:
  - job: C1
    steps:
    - script: echo hello from Stage C