trigger: none
name: ColorOutput

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    ##[group]Beginning of a group
    ##[warning]Warning message
    ##[error]Error message
    ##[section]Start of a section
    ##[debug]Debug text
    ##[command]Command-line being run
    ##[endgroup]

    echo "##[group]Beginning of a group"
    echo "##[warning]Warning message"
    echo "##[error]Error message"
    echo "##[section]Start of a section"
    echo "##[debug]Debug text"
    echo "##[command]Command-line being run"
    echo "##[endgroup]""
  displayName: 'Run a multi-line script'
