trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  myInner: someValue
  myOuter: $(myInner)

steps:
- script: echo $(myOuter)  # prints "someValue"
  displayName: Variable is $(myOuter)  # display name is "Variable is $(myInner)"
  
- script: echo $(myOuter)  # prints "someValue"
  displayName: Variable is ${{ variables.myOuter }}  # display name is "Variable is $(myInner)"